### ISSUE TITLE
[toolbox-export] Add command-line option to pass container name when creating desktop files

### ISSUE THREAD

**Issue by lbssousa** [A6GibKm/silverblue-tools#1]
Currently `toolbox-export` only creates desktop files assuming the default toolbox container name (e.g. `fedora-toolbox-XX`). It would be awesome if you can add a command-line option to pass the toolbox container name when creating the desktop files, so that it can fill the `Exec` / `TryExec` lines with the correct command line (e.g. `toolbox run --container [CONTAINER-NAME] ...`)

**Comment by A6GibKm** [comment]
Thanks for reporting.

Fixed in https://github.com/A6GibKm/silverblue-tools/commit/ec4e95756987b687d785738e1addb49d562e7423.

**Comment by mikunimaru** [comment]
It is always better to specify the container name, as all shortcuts will be destroyed if the default container changes due to Fedora upgrades.
