### ISSUE TITLE
[toolbox-export] Add command-line options to the README

### ISSUE THREAD

**Issue by ghost** [A6GibKm/silverblue-tools#5]
I think it would be good to add the command-line options to the README for better visibility.

Maybe something like this under the usage section?

> **--list** : List desktop files inside the toolbox
> **--uninstall** : Uninstall related files
> **-c** | **--container** : Name of the toolbox container

**Comment by A6GibKm** [comment]
Thanks for the suggestion, unfortunately, thats the purpose of the --help, or -h flag. I am not inclined to add maintenance burden in this area.

**Comment by JBallard22** [comment]
Good point, I just think the README should mention there are command-line flags at all as I assumed it "just worked" based on the example shown, and think others might do the same.
